/**
 * \file src/dcs/math/stats/distribution/degenerate.hpp
 *
 * \brief Degenerate distribution.
 *
 * Copyright (C) 2009-2012  Distributed Computing System (DCS) Group,
 *                          Computer Science Institute,
 *                          Department of Science and Technological Innovation,
 *                          University of Piemonte Orientale,
 *                          Alessandria (Italy).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * \author Marco Guazzone (marco.guazzone@gmail.com)
 */

#ifndef DCS_MATH_STATS_DISTRIBUTION_DEGENERATE_HPP
#define DCS_MATH_STATS_DISTRIBUTION_DEGENERATE_HPP


#include <cstddef>
#include <dcs/macro.hpp>
#include <dcs/math/policies.hpp>
#include <iostream>
#include <vector>


namespace dcs { namespace math { namespace stats {

/**
 * \brief Degenerate distribution.
 *
 * A <em>degenerate distribution</em> is the probability distribution of the
 * <em>constant random variable</em>, a discrete random variable whose support
 * consists of only one value.
 *
 * The degenerate distribution is localized at a point \f$k_0\f$ on the real
 * axis.
 * The probability mass function is given by:
 * \f{equation*}{
 *   f(k;k_0)=\begin{cases}
 *              1, & \text{if }k=k_0 \\
 *              0, & \text{if }k \ne k_0
 *             \end{cases}
 * \f}
 * The cumulative distribution function of the degenerate distribution is:
 * \f{equation}{
 *   F(k;k_0)=\begin{cases}
 *   			1, & \text{if }k\ge k_0 \\
 *   			0, & \text{if }k<k_0
 *   		  \end{cases}
 * \f}
 *
 * \author Marco Guazzone, &lt;marco.guazzone@mfn.unipmn.it&gt;
 */
template <
	typename RealT=double,
	typename PolicyT=::dcs::math::policies::policy<>
>
class degenerate_distribution
{
	public: typedef RealT support_type;
	public: typedef RealT value_type;
	public: typedef PolicyT policy_type;


	/// A constructor.
	public: explicit degenerate_distribution(support_type v=support_type/*0*/())
	: k0_(v)
	{
	}


	/// Return the constant value
	public: support_type value() const
	{
		return k0_;
	}


	/// Compute the PDF for the given value.
	public: value_type pdf(support_type x) const
	{
		return (x == k0_) ? 1.0 : 0.0;
	}


	/// Compute the CDF for the given value.
	public: value_type cdf(support_type x) const
	{
		return (x >= k0_) ? 1.0 : 0.0;
	}


	// Compute the quantile value corresponding to the given probability value.
	public: support_type quantile(value_type p) const
	{
		return k0_;
	}


	/// Generate a random variate distributed according to this distribution and
	/// generated by means of the given uniform random number generator.
	public: template <typename UniformRandomGeneratorT>
		support_type rand(UniformRandomGeneratorT& rng) const
	{
		DCS_MACRO_SUPPRESS_UNUSED_VARIABLE_WARNING( rng );

		return k0_;
	}


	/// Generate \a n random variates distributed according to this distribution
	/// and generated by means of the given uniform random number generator.
	public: template <typename UniformRandomGeneratorT>
		::std::vector<support_type> rand(UniformRandomGeneratorT& rng, ::std::size_t n) const
	{
		DCS_MACRO_SUPPRESS_UNUSED_VARIABLE_WARNING( rng );

		return ::std::vector<support_type>(n, k0_);
	}


	public: value_type mean() const
	{
		return k0_;
	}


	public: value_type median() const
	{
		return k0_;
	}


	public: value_type variance() const
	{
		return 0;
	}


	/// The solely value
	private: support_type k0_;
};


template <typename RealT, typename PolicyT>
RealT mean(degenerate_distribution<RealT,PolicyT> const& d)
{
	return d.mean();
}


template <typename RealT, typename PolicyT>
RealT variance(degenerate_distribution<RealT,PolicyT> const& d)
{
	return d.variance();
}


template <typename RealT, typename PolicyT>
RealT standard_deviation(degenerate_distribution<RealT,PolicyT> const& d)
{
	return ::std::sqrt(d.variance());
}


template <
	typename CharT,
	typename CharTraitsT,
	typename RealT,
	typename PolicyT
>
::std::basic_ostream<CharT,CharTraitsT>& operator<<(::std::basic_ostream<CharT,CharTraitsT>& os, degenerate_distribution<RealT,PolicyT> const& dist)
{
	os << "Degenerate(" << dist.value() << ")";

	return os;
}

}}} // Namespace dcs::math::stats
#endif // DCS_MATH_STATS_DISTRIBUTION_DEGENERATE_HPP
